DELETE http://localhost:8080/api/employee/6
Accept: application/json

###
PUT http://localhost:8080/api/employees
Content-Type: application/json

{
  "id": "6",
  "firstName": "Toni",
  "lastName": "Schmidbauer",
  "email": "toni@stderr.at"
}

###
POST http://localhost:8080/api/employees
Content-Type: application/json

{

  "firstName": "Toni",
  "lastName": "Schmidbauer",
  "email": "toni@schmidbauer.cc"
}

###
GET http://localhost:8080/api/employees/2
Accept: application/json

###
GET http://localhost:8080/api/employees
Accept: application/json


