GET http://localhost:8080/api/employees/9999
Accept: application/json

###

### Delete employee
DELETE http://localhost:8080/api/employee/6
Accept: application/json

### Update employee
PUT http://localhost:8080/api/employees
Content-Type: application/json

{
  "id": "7",
  "firstName": "Toni",
  "lastName": "Schmidbauer",
  "email": "toni@stderr.at"
}

### Create employee
POST http://localhost:8080/api/employees
Content-Type: application/json

{

  "firstName": "Toni",
  "lastName": "Schmidbauer",
  "email": "toni@schmidbauer.cc"
}

### Get employee
GET http://localhost:8080/api/employees/2
Accept: application/json

### Get all employees
GET http://localhost:8080/api/employees
Accept: application/json

